# Generated by Django 4.1.3 on 2022-11-05 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
